enum ErrorCode {
  INTERNAL_ERROR,
  UNKNOWN_ERROR,
  INVALID_ID,
  INVALID_VALUE_OBJECT_PARSE,
  NAME_TOO_SHORT,
  NAME_TOO_LONG,
  NAME_INVALID_CHARACTERS,
  INVALID_EMAIL,
  CODE_TOO_SHORT,
  CODE_TOO_LONG,
  CODE_INVALID_CHARACTERS,
  EXPIRED_SHORTENED_LINK,
  USER_NOT_FOUND_BY_EMAIL,
  INVALID_PASSWORD,
  EMAIL_ALREADY_TAKEN,
  EXPIRED_TOKEN,
  INVALID_TOKEN,
  USER_NOT_FOUND,
  CODE_ALREADY_TAKEN,
  INVALID_LINK,
  SHORTENED_LINK_NOT_FOUND,
}

export function errorCodeToString(errorCode: ErrorCode) {
  return ErrorCode[errorCode];
}

export default ErrorCode;
